#!/bin/bash
echo ---------- RUNNING FIRST PDFLATEX PASS ----------
pdflatex LV3_AIAA.tex | grep -i warning 
echo ---------- RUNNING BIBTEX PASS ----------
bibtex LV3_AIAA
echo ---------- RUNNING SECOND PDFLATEX PASS ----------
pdflatex LV3_AIAA.tex | grep -i warning 
echo ---------- RUNNING FINAL PDFLATEX PASS ----------
# pdflatex LV3_AIAA.tex | tee 'out.log'
pdflatex LV3_AIAA.tex > 'out.log'
echo ---------- WARNINGS ----------
grep -i warning out.log
while getopts ph FLAG
do
	case $FLAG in
		p)
			printf '\nabout to open the pdf...\n'
			sleep 3
			evince LV3_AIAA.pdf &
			;;
		[h\?])
			echo -e \\n'-p'
			echo -e \\t'display the pdf after compiling'
			echo -e \\n'-h'
			echo -e \\t'show this help'
	esac
done
